name: Build TechDocs
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install mkdocs
      run: |
        pip install mkdocs-techdocs-core

    - name: Build TechDocs
      run: |
        mkdocs build

    - name: Upload to S3
      uses: carlos/s3-sync-action@v0.5.3
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_TECHDOCS }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
